version: "3.8"
services:
  zookeeper:
    deploy:
      replicas: 1
    image: zookeeper-3.9.2:latest
    ports:
      - "2181:2181"
    restart: always
  kafka-server:
    depends_on:
      - zookeeper
    deploy:
      replicas: 1
    env_file:
      - ./kafka_server/.env
    image: kafka-3.4.1-server.docker-compose:latest
    ports:
      - "9092:9092"
    restart: always
  prometheus:
    depends_on:
      - kafka-server
    image: prometheus-2.54.1:latest
    ports:
      - "9000:9000"
    restart: always
