version: "3.8"
services:
  zookeeper:
    deploy:
      replicas: 1
    image: zookeeper-3.9.2:latest
    ports:
      - "2181:2181"
    restart: always
  kafka-server:
    depends_on:
      - zookeeper
    deploy:
      replicas: 1
    env_file:
      - ./kafka_server/.env
    image: kafka-3.4.1-server:latest
    ports:
      - "9092:9092"
    restart: always
  kafka-producer:
    depends_on:
      - kafka-server
    deploy:
      replicas: 1
    env_file:
      - ./kafka_producer/.env
    image: kafka-3.4.1-producer:latest
    restart: always
  kafka-consumer:
    depends_on:
      - kafka-server
    deploy:
      replicas: 1
    env_file:
      - ./kafka_consumer/.env
    image: kafka-3.4.1-consumer:latest
    restart: always
  kafdrop-server:
    depends_on:
      - kafka-server
    deploy:
      replicas: 1
    env_file:
      - ./kafdrop_server/.env
    image: kafdrop-4.0.3-snapshot:latest
    ports:
      - "9000:9000"
    restart: always
