version: "3.8"

services:
  kafka_producer:
    # Must build image first - `docker build -t kafka_producer ~/kafka_producer/.`
    image: kafka_producer
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    secrets:
      - environment_variables
    networks:
      - my_network

secrets:
  environment_variables:
    external: true

networks:
  my_network:
    driver: overlay
