apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.kubernetes.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.kubernetes.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - image: grafana-11.2.0:latest
          imagePullPolicy: IfNotPresent # Only pull the image if not present locally
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
