apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.kubernetes.yaml
    kompose.service.type: nodeport
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: kafdrop-server
  name: kafdrop-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafdrop-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.kubernetes.yaml
        kompose.service.type: nodeport
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: kafdrop-server
    spec:
      containers:
        - env:
            - name: KAFKA_BROKERCONNECT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKERCONNECT
                  name: kafdrop-server-env
          image: kafdrop-4.0.3-snapshot:latest
          imagePullPolicy: IfNotPresent # Only pull the image if not present locally
          name: kafdrop-server
          ports:
            - containerPort: 9000
              protocol: TCP
      restartPolicy: Always
