apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.kubernetes.yaml
    kompose.service.type: nodeport
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: kafdrop-server
  name: kafdrop-server
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: kafdrop-server
  type: NodePort
