apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.kubernetes.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-producer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.kubernetes.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: kafka-producer
    spec:
      containers:
        - env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  key: APP_ENV
                  name: kafka-producer-env
            - name: DOCKER_BROKER_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_BROKER_ADDRESSES
                  name: kafka-producer-env
            - name: LOCAL_BROKER_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  key: LOCAL_BROKER_ADDRESSES
                  name: kafka-producer-env
            - name: LOG_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  key: LOG_FILE_PATH
                  name: kafka-producer-env
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: kafka-producer-env
            - name: MESSAGE_LIMIT
              valueFrom:
                configMapKeyRef:
                  key: MESSAGE_LIMIT
                  name: kafka-producer-env
            - name: SLEEP_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: SLEEP_TIMEOUT
                  name: kafka-producer-env
            - name: TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  key: TOPIC_NAME
                  name: kafka-producer-env
          image: kafka-3.4.1-producer:latest
          imagePullPolicy: IfNotPresent # Only pull the image if not present locally
          name: kafka-producer
      restartPolicy: Always
