apiVersion: v1
data:
  APP_ENV: development
  CONSUMER_GROUP_ID: example_consumer_group
  DOCKER_BROKER_ADDRESSES: kafka-server:9093
  LOCAL_BROKER_ADDRESSES: kafka-server:9092
  LOG_FILE_PATH: logs/development.log
  LOG_LEVEL: development
  TOPIC_NAME: example-topic-1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: kafka-consumer-kafka-consumer-env
  name: kafka-consumer-env
