apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.kubernetes.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: kafka-server
  name: kafka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.kubernetes.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: kafka-server
    spec:
      containers:
        - env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  key: APP_ENV
                  name: kafka-server-env
            - name: BROKER_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  key: BROKER_ADDRESSES
                  name: kafka-server-env
            - name: LOG_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  key: LOG_FILE_PATH
                  name: kafka-server-env
          image: kafka-3.4.1-server.kubernetes:latest
          imagePullPolicy: IfNotPresent # Only pull the image if not present locally
          name: kafka-server
          ports:
            - containerPort: 9092
              protocol: TCP
      restartPolicy: Always
