apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.kubernetes.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.kubernetes.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: zookeeper
    spec:
      containers:
        - image: zookeeper-3.9.2:latest
          imagePullPolicy: IfNotPresent # Only pull the image if not present locally
          name: zookeeper
          ports:
            - containerPort: 2181
              protocol: TCP
      restartPolicy: Always
